### ISSUE TITLE
iostat.py produces incorrect await

### ISSUE THREAD

**Issue by zeocio** [OpenTSDB/tcollector#177]
The current iostat.py logic computes a ratio of ticks/ios whereas the correct logic computes a ratio of deltas: delta(ticks)/delta(ios) as in line 938 and 941 of https://github.com/sysstat/sysstat/blob/master/iostat.c

**Comment by vasiliyk** [comment]
I still hope to get pull request with updated functionality. Anyone?

**Comment by zeocio** [comment]
here:  https://github.com/OpenTSDB/tcollector/pull/199

**Comment by vasiliyk** [comment]
Fixed with pull request https://github.com/OpenTSDB/tcollector/pull/199.
