### ISSUE TITLE
Restructure of collectors/*

### ISSUE THREAD

**Issue by kylemallory** [OpenTSDB/tcollector#190]
I would like to propose a restructuring of the /collectors directory, such that all collectors are disabled by default, but can be enabled or disabled easily, preferably without a restart of tcollector.  Without giving it too much thought, I'm leaning toward something similar to apache's a2ensite/a2enmod functionality.  By default, all collectors would be placed in the folder './collectors/available', which is essentially ignored by tcollector.  Collectors are enabled by creating a symlink from ./collectors/0/collector.py to ./collectors/available/collector.py.  Collectors are disable by removing the symlink (this would require changes to tcollector.py to look for modules that are running, but which a symlink does not exist for, and kill the collector if it doesn't exit on its own after a certain time).

I would also like to propose refactoring the config file, to be directly tied to the collector, though I have less of a suggestion on how to structure this; perhaps combining both the config and code into a single folder that is placed under the collectors directory, ie, ./collectors/0/my_collector.d/{main.py|config.py}. However, I am also contemplating placing configs in /etc/tcollector/module_name/, and other alternatives.

Background:  We have a VM farm of about 15 "development environments", which are one or more hosts that mimic our multi-host production environment.  Each development team has access to 1 or 2 of these dev environments.  I would like to use tcollector to gather metrics from each development environment so that the development teams can monitor the status of their environment.

In order to manage these 20 hosts, I would like to deploy tcollector via puppet.  Since some collectors require specific configuration changes (database config, custom tags, etc), and due to current, active development of new collectors specific to our environment, I'm configuring puppet to clone tcollector from our local fork of the github repo; and then template the individual configs.  I intend to use the same fork to submit patches back to the master, so I don't want to store our custom configs in our tcollector repo.  Likewise, however, I do not want new collectors and configs coming down-stream and automatically being included and executed.  Additinally, I have ran into problems in the past where an invalid module config for a disabled collector will bring down tcollector completely due to tcollector evaluating all configs in ./collector/etc, regardless of whether the parent collector is enabled or not.

I would certainly like to have a further discussion of this, and see where the rest of the OpenTSDB/tcollector team is with this.  I am happy to do the refactoring and code contributions where I am able.  If this issue-request isn't the best place for that discussion, please direct me to the proper channel.

**Comment by johann8384** [comment]
The way I have typically handled this is I have a TCollector RPM which is sans collectors. Then I have a define in Puppet something like: 

```
::tcollector::collector { 'hbase-regionserver':
  interval => 15,
}
```

The define allows me to specify a source or content entry, as well as come configuration parameters and it will write out a config class from a template and place the collector onto the system.

By default, this sources the collector script from tcollector/files/usr/local/tcollector/collectors/ in the Puppet tree and places it onto the box. 

I have a class ::tcollector::collectors::standard that includes the base collectors I want on each box and their desired configurations.

We are using Hiera so I can override a few parameters to ::collectors::standard per environment quite easily there.

**Comment by vasiliyk** [comment]
I like the idea.
It is one thing if we have only limited set of systems collectors but we have a lot of collectors that depends on external software like DBs, web-servers etc so their rerun without correspondent software (or appropriate configuration) is just waste of resources.

All collectors placed in the folder './collectors/available', which is ignored by tcollector.
Collectors are enabled by creating a symlink from ./collectors/0/collector.py to ./collectors/available/collector.py.

Not everybody use distribution packages so I believe that system directories /etc/tcollector/ and so on are for packages. Let us keep it as it is for now.

**Comment by stuart-warren** [comment]
I thought collectors that didn't find their DB/server etc exited with a code and weren't run again (for an extended period)? Maybe just fix that functionality on collectors that don't behave.

**Comment by vasiliyk** [comment]
@stuart-warren we don't need to start what we don't want to use, and there is no sense to repeat it after restart

**Comment by kylemallory** [comment]
Another, more important aspect of this issue that I briefly hit on originally, is the configuration of each collector.  Many of the collectors use python code for their configuration, which is fine.  However, when tcollector is started, it attempts to execute/parse ALL of the /etc config code, regardless of whether the actual collector can (or should) run.  If the config code has errors, it can prevent tcollector from starting any other collectors.  As I see it, the arguments are:

1) Don't run code that's not explicitely configured to run.  Period.  Not having a fence to corral potentially bad collectors (environmental failures, missing dependencies, etc) is dangerous, nevermind irresponsible; I do appreciate that 'bad' code currently is removed from execution if it fails, etc; but there should also be a clear way to prevent code from executing in the first place.
2) Configurations should be bound to the collector.  When a collector is disabled, all files associated with that collector should be removed from possible execution.
3) There should be a simple mechanism to enable/disable the execution of collectors.  Ideally, the enabling/disabling should be done atomically for all files associated with a collector; Ie, you shouldn't need to copy/move/rename multiple files (config or otherwise) to enable/disable any single collector.

I think #2 and #3 are essentially restating the same thing; but.. whatever.  ;-)

@johann8384 Thanks for the puppet suggestion.  I'll look into it; the package management aspect is something I'll have to dig into.  I'm not opposed to building packages without the collectors, but its not how we're doing it now.

**Comment by tsuna** [comment]
I think what @kylemallory suggests sounds fine.  The current system based on directories was very simple / rudimentary.  With a little luck, you won't even need much changes to tcollector, since it already periodically look for files that are gone from the filesystem (it doesn't use inotify for no good reason).  So once you add the symlink, it should pick it up, and once you remove the symlink, it should kill the collector.  That should pretty much work already today.

I've never really been super satisfied with the way to configure the collectors either.  A lot of these things were built in a rather ad-hoc fashion, often by going after the simplest way possible to implement them (which led to things like tcollector crapping out if you have a syntax error in a Python file used as a config).

**Comment by itamarst** [comment]
Looks like this issue was closed by mistake, and should still be open?

**Comment by vasiliyk** [comment]
Implemented with commit https://github.com/OpenTSDB/tcollector/commit/881e2157dfbdc9e7e9f7160508e41f454e0b0bb7
Documentation updated to reflect the change: http://opentsdb.net/docs/build/html/user_guide/utilities/tcollector.html
