### ISSUE TITLE
Uncaught exception seen in the tcollector.log stack trace , occurs frequently,

### ISSUE THREAD

**Issue by Divsnarayan** [OpenTSDB/tcollector#191]
2015-01-23 10:39:14,115 tcollector[7958] ERROR: uncaught exception in stdout read
Traceback (most recent call last):
  File "/opt/tcollector/tcollector.py", line 155, in read
    self.buffer += self.proc.stdout.read()
AttributeError: 'NoneType' object has no attribute 'stdout'

**Comment by vasiliyk** [comment]
Hello.

Please, tell us more about your system, tcollector options, and configuration.

**Comment by johann8384** [comment]
As you can see in this section, 

```
try:
  self.buffer += self.proc.stdout.read()
  if len(self.buffer):
    LOG.debug('reading %s, buffer now %d bytes', self.name, len(self.buffer))
except IOError, (err, msg):
  if err != errno.EAGAIN:
      raise
except:
  # sometimes the process goes away in another thread and we don't
  # have it anymore, so log an error and bail
  LOG.exception('uncaught exception in stdout read')
  return
```

That message is to let the us know that we tried to read something output by a collector but in the process of doing so, the collector went away. This is not a problem with TCollector, perhaps the error message should be more clear. It isn't an uncaught exception, we caught it, and are telling you so.
