### ISSUE TITLE
Upgrading Tcollector to Python 3

### ISSUE THREAD

**Issue by aniketmaithani** [OpenTSDB/tcollector#218]
I was hoping that if we could upgrade some of the `collectors` to Python3. I am happy to take this task and will be sending a PR soon. :)

**Comment by vasiliyk** [comment]
Please remember that we need to preserve python 2.6 compatibility.

**Comment by johann8384** [comment]
@aniketmaithani Do you still have interest in doing this?

**Comment by xavierhardy** [comment]
Are you still interested in preserving Python 2.6 compatibility? This is just a matter of fixing tests.py (which is not 2.6-compatible BTW).
