### ISSUE TITLE
How to do troubleshooting?

### ISSUE THREAD

**Issue by whitelilis** [OpenTSDB/tcollector#220]
When I can't get some metrics, how to do troubleshooting?

**Comment by vasiliyk** [comment]
Hello.

Please, start from 
http://opentsdb.net/docs/build/html/user_guide/troubleshooting.html
http://opentsdb.net/docs/build/html/user_guide/logging.html

if you still have questions please submit them to:
https://groups.google.com/forum/#!forum/opentsdb.
