### ISSUE TITLE
g1gc not producing output

### ISSUE THREAD

**Issue by dprime** [OpenTSDB/tcollector#222]
Hi,

I've just tried to use the bundled g1gc plugin and it's not doing a lot. Just spitting out a load of 0 counters.
My gc log is being written to and it's in the place I've pointed the plugin to.

I've configured the log directory and have tried running the JVM in a variety of gc printing modes and all I ever get is:

jvm.gc.g1.event.count 1443106713 0 event=young
jvm.gc.g1.event.count 1443106714 0 event=mixed
jvm.gc.g1.event.count 1443106714 0 event=remark
jvm.gc.g1.event.count 1443106714 0 event=fullgc
jvm.gc.g1.event.count 1443106714 0 event=initialmark

Over and over. I'm not sure what I'm doing wrong. Has anyone else got this working? If so, what combination of gc & log settings did you use?

Cheers,
David

**Comment by dprime** [comment]
I've dug around in the code a bit and it looks like the parser is simply out of date, sadly. I've scraped the data I need from JMX for now as I'm not good at python and re-writing the parser would be a lot more work. The plugin should probably be removed, or at least annotated a bit with information about which versions and combinations of GC flags it supports.

**Comment by vasiliyk** [comment]
Hello @dprime. We depend on collector's authors to keep collectors updated. Usually if someone added collector she wanted it to keep working.

Hello @yaoshengzhe. Are you interested in updating of g1gc collector?

**Comment by yaoshengzhe** [comment]
@dprime would you be able to share your log ? The g1gc parser is written according to the official doc. Have you enabled -XX:+PrintGCDetails ? This post would be a good reference: https://blogs.oracle.com/poonam/entry/understanding_g1_gc_logs

**Comment by johann8384** [comment]
@dprime Are you still having an issue? I'd like to close this out if not.

**Comment by dprime** [comment]
Hi, I stopped using this tcollector for this reason so I don't know if it's still present or not. It's certainly not an issue for me.

**Comment by HariSekhon** [comment]
This is still broken.

Any chance of a fix?
