### ISSUE TITLE
elasticsearch.py boolean data values

### ISSUE THREAD

**Issue by mlosapio** [OpenTSDB/tcollector#224]
We're seeing 400 errors in opentsdb when posting metrics to the HTTP interface for opentsdb when the metric value is a boolean

AFAIK - boolean values are not supported value types in opentsdb. If there's a desired standard here like converting booleans to integer 0's and 1's I'll commit a patch here. 

Specifically; 

        "metric": "elasticsearch.cluster.timed_out",
        "tags": {
            "cluster": "geologist",
            "environment": "production",
            "function": "slate",
            "host": "mycluster.hostname.local",
            "region": "virginia",
            "stack": "mycluster"
        },
        "timestamp": "1444846445",
        "value": "False"
    },

**Comment by vasiliyk** [comment]
You are right as per HTTP API value can hold only integer or a floating point value.
HTTP API put: http://opentsdb.net/docs/build/html/api_http/put.html

If you still believe that boolean value should be supported open issue under  https://github.com/OpenTSDB/opentsdb.

Thanks.
