### ISSUE TITLE
Runabove compatibility

### ISSUE THREAD

**Issue by benrubson** [OpenTSDB/tcollector#225]
Hello,

Could it be possible to make tcollector compatible with Runabove please ?
https://www.runabove.com/iot-paas-timeseries.xml

Runabove needs a token/appname to authorize connections :
``HOST="https://appname:token@opentsdb.iot.runabove.io"``

Thank you !

**Comment by johann8384** [comment]
I'll investigate being able to do this, but it will take some effort. 

An example Client:
https://github.com/runabove/iot-push-examples/blob/master/Python/python-client-telnet.py
