### ISSUE TITLE
Millisecond precision in tcollector.py

### ISSUE THREAD

**Issue by phil-arista** [OpenTSDB/tcollector#230]
At line [54](https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L54) you set the max ts to 10 digits which implies second precision.  In the tcollector docs you mention that you can use 10 second precision but specify ms with NNNNNNNNNN.MMM but this fails the regex match on line 328.

[Pythex example](http://pythex.org/?regex=%5E(%5B-_.%2Fa-zA-Z0-9%5D%2B)%5Cs%2B(%5Cd%2B)%5Cs%2B(%5CS%2B%3F)((%3F%3A%5Cs%2B%5B-_.%2Fa-zA-Z0-9%5D%2B%3D%5B-_.%2Fa-zA-Z0-9%5D%2B)*)%24&test_string=sys.blah.blah.blah%201222333444%2014.1%20host%3Dbob%0Asys.blah.blah.blah%201222333444.000%2014.1%20host%3Dbob%0Asys.blah.blah.blah%201222333444555%2014.1%20host%3Dbob&ignorecase=0&multiline=1&dotall=0&verbose=0)

Wondering how to create a collector that reports ms precision?

**Comment by phil-arista** [comment]
Ping

**Comment by tsuna** [comment]
I don't think that's supported yet. Do you wanna send a pull request to fix the code so it accepts millisecond precision?
