### ISSUE TITLE
error running tcollector 

### ISSUE THREAD

**Issue by githubu1** [OpenTSDB/tcollector#235]
Today i have downloaded (Jan,21,2015) tcollecter and i got this error while running the tcollector.

This is the errors from /var/log/tcollector.log

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/XXXX/tcollector/tcollector.py", line 304, in run
    self.process_line(col, line)
  File "/home/XXXX/tcollector/tcollector.py", line 365, in process_line
    elif timestamp >= MAX_REASONABLE_TIMESTAMP:
UnboundLocalError: local variable 'MAX_REASONABLE_TIMESTAMP' referenced before assignment

I replaced tcollector.py with a previous copy ( downloaded on Jan ,15 ,2016) to overcome this error.

This is the difference between the working one and error one 

diff tcollector.py /error/tcollector.py 
339a340,344
>         # If there are more than 11 digits we're dealing with a timestamp
>         # with millisecond precision
>         if len(str(timestamp)) > 11:
>             MAX_REASONABLE_TIMESTAMP = MAX_REASONABLE_TIMESTAMP * 1000
> 
535c540
<             
---
> 

Thanks

**Comment by vasiliyk** [comment]
Hello.  I would like to add @phil-arista to our conversation.

**Comment by phil-arista** [comment]
Error doesn't make sense since it's a global var.

**Comment by phil-arista** [comment]
Aye, this is my fault - I'll PR a fix asap

**Comment by phil-arista** [comment]
Sorry guys - silly mistake on my part.  The PR listed above has the simple fix for this.

**Comment by vasiliyk** [comment]
@phil-arista quickly fixed is not broken) sure we will put a bit more effort in testing next time. I missed it too with quick look.
