### ISSUE TITLE
Time for a release

### ISSUE THREAD

**Issue by johann8384** [OpenTSDB/tcollector#245]
It is time to make a release of TCollector.

I believe there should be a release tag here on GH, I can also make RPM and Deb packages (probably) to attach to the release.

There have been some significant improvements merged in the last 6 months and it would be a great way to highlight those.

**Comment by tsuna** [comment]
+1 :)

**Comment by johann8384** [comment]
Items tagged with [1.3.0](https://github.com/OpenTSDB/tcollector/issues?utf8=%E2%9C%93&q=milestone%3A1.3.0+)

Once all of the issues are closed and PR merged for this milestone I should be able to create the CHANGELOG.
