### ISSUE TITLE
Make tcollector more FreeBSD friendly ?

### ISSUE THREAD

**Issue by benrubson** [OpenTSDB/tcollector#251]
Hello,

What about making tcollector more FreeBSD friendly ?
For example, python has the following path on FreeBSD :
`/usr/local/bin/python`
Perhaps we could modify the shebang to `env python` in all the .py files of the distribution ?

In addition, what about rearranging the `collectors` folder with a `linux` folder, a `freebsd` folder and an `application` folder ?
We would then be able to populate the `freebsd` folder with new scripts, and share existing scripts between the `linux` and the `application` folder.
For example :
- `ifstat.py`, `iostat.py` would go to the `linux` folder ;
- `zfsiostats.py`, `mysql.py` would go to the `application` folder.

This would make Tcollector more FreeBSD compliant.

Thank you very much !

Ben

**Comment by johann8384** [comment]
I could do this as a part of the "available" folder PR. I'll also need to check out the recent RPM changes and make sure that it works with those. 

There are some OSX specific collectors floating around also, I may ping a few other authors on Github and ask if they would like to contribute them.

**Comment by benrubson** [comment]
What is the "available" folder PR ?

**Comment by johann8384** [comment]
https://github.com/OpenTSDB/tcollector/pull/239

**Comment by johann8384** [comment]
@benrubson How are we doing on this? Any more items we should close out before closing this issue?

**Comment by benrubson** [comment]
Yes we could close this, as main expected change will be done through #239.
New collectors will be written for FreeBSD through new pull requests.
So let's close this :+1:

**Comment by vasiliyk** [comment]
implemented and merged with the commit https://github.com/OpenTSDB/tcollector/commit/881e2157dfbdc9e7e9f7160508e41f454e0b0bb7
