### ISSUE TITLE
RPM doesn't clean up after itself on uninstall

### ISSUE THREAD

**Issue by phil-arista** [OpenTSDB/tcollector#278]
Need to rm -rf /usr/local/tcollector after rpm -e.

Also remove files in /etc/init.d, etc when needed.

I can do this if you'd like?

**Comment by johann8384** [comment]
A PR for this would be greatly appreciated!

**Comment by phil-arista** [comment]
Sure, you can assign it to me

**Comment by johann8384** [comment]
Do you have an ETA for this? I'd like to get the release cut by Friday.

**Comment by phil-arista** [comment]
I'll work on it today.

**Comment by phil-arista** [comment]
PR submitted.
