### ISSUE TITLE
Put a configuration example in config.py

### ISSUE THREAD

**Issue by benrubson** [OpenTSDB/tcollector#279]
Hello,

Could it be possible to add a configuration example (as a comment) in `config.py` please ?
For example, how to add the following parameters into the config file :
`--ssl --http -L my.host --http-username=XXX --http-password=YYY`

Thank you very much :+1:

Ben

**Comment by johann8384** [comment]
I'm working on a small change to the optionsparser function which will read defaults from a config, then override them from the command line. This will replace the defaults in the code with default in a config.

**Comment by benrubson** [comment]
Sounds good ! :+1:

**Comment by benrubson** [comment]
Excellent, thank you very much Jonathan !
