### ISSUE TITLE
Issue with cpus_pctusage.py

### ISSUE THREAD

**Issue by dileepindla** [OpenTSDB/tcollector#297]
cpus_pctusage.py not generating any metrics.Can any one please tell me is it issue with collector or I need to modify anything.

**Comment by benrubson** [comment]
You need mpstat command on Linux, top command on FreeBSD.
Then cpus_pctusage.py should generate metrics.

If you are on Linux, install mpstat ?

**Comment by benrubson** [comment]
Of course let us know :+1:

**Comment by dileepindla** [comment]
Yeah  mpstat is already installed...

**Comment by benrubson** [comment]
Could you give me the raw output of the following command ?
`mpstat -P ALL 2`

**Comment by dileepindla** [comment]
```
09:16:33 AM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest   %idle
09:16:35 AM  all    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00  100.00
09:16:35 AM    0    0.00    0.00    0.50    0.00    0.00    0.00    0.00    0.00   99.50
09:16:35 AM    1    0.50    0.00    0.00    0.00    0.00    0.00    0.00    0.00   99.50
09:16:35 AM    2    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00  100.00
09:16:35 AM    3    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00  100.00
```

**Comment by benrubson** [comment]
OK, understood, let me think about a patch :+1:

**Comment by dileepindla** [comment]
Thank you ,will wait for your reply.

**Comment by benrubson** [comment]
See #298 for a fix !

**Comment by dileepindla** [comment]
Thank you !! Now its working....
