### ISSUE TITLE
tcollector.py line 814 and line 838

### ISSUE THREAD

**Issue by erdeerdeerde** [OpenTSDB/tcollector#305]
If installed via debian package, starting tcollector fails because in line 814 a file is included (from collectors.etc import config) which is not under the path of the tcollector.py executable (/usr/bin/tcollector as opposed to /usr/lib/tcollector/)

I also noticed that when the exception is thrown in line 815, the following code also fails because in line 837 a variable is referenced that has not previously been assigned a value.

**Comment by johann8384** [comment]
It sounds like we need to modify the Python path there. I will investigate.

**Comment by johann8384** [comment]
Can you send me a link to the lines you are mentioning? Line 837 in my editor is: 
https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L837
            'logfile': '/var/log/tcollector.log',

**Comment by erdeerdeerde** [comment]
https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L814
and
https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L838


On 03/21/2016 08:49 PM, Jonathan Creasy wrote:
> Can you send me a link to the lines you are mentioning? Line 837 in
> my editor is: 
> https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L837
>
> 
'logfile': '/var/log/tcollector.log',

**Comment by johann8384** [comment]
Sorry, that was obvious, I just wanted to make sure I was looking at the right problem. I made a patch, I'll try and get time to test it. I have a few other things to test on Debian priori to the 1.3.1 release. I'm also hoping to have deb packages, not just rpm, for that one.
