### ISSUE TITLE
tcollector on remotely

### ISSUE THREAD

**Issue by phanikumarp** [OpenTSDB/tcollector#313]
How get remote date from tcollector ( based on provided ip or host get data from remotely)

**Comment by johann8384** [comment]
This sounds like a question for the mailing list, but I think the answer is that TCollector isn't for collecting remote data. Typically you run it on each machine and it collects data from that machine. You *could* use the tcp_bridge and udp_bridge collectors to accept data from remote machines, but the use cases for that would be pretty limited.

https://groups.google.com/forum/#!forum/opentsdb
