### ISSUE TITLE
Issue Mysql

### ISSUE THREAD

**Issue by phanikumarp** [OpenTSDB/tcollector#314]
how to get mysql data from container(docker)
mysql is resides in container ,i want get the data from mysql using tcollecteor, i don't know is it possible or not.

**Comment by pradeepchhetri** [comment]
@phanikumarp By looking at the mysql plugin, currently you would need to start mysql docker container with these flags:

`-v /tmp:/tmp -v /var/lib/mysql:/var/lib/mysql -v /var/run/mysqld:/var/run/mysqld`

**Comment by johann8384** [comment]
That would work, we could modify the mysql collector to handle multiple instances also.

Feel free to ask questions on the mailing list: https://groups.google.com/forum/#!forum/opentsdb

**Comment by pradeepchhetri** [comment]
@johann8384 Agreed. Will have a look at doing that soon .. it makes sense in container world. All our tcollector scripts needs to be updated for that.
