### ISSUE TITLE
Documentation does not address new configuration file

### ISSUE THREAD

**Issue by Andi24** [OpenTSDB/tcollector#325]
I had a look in your commit history and saw that you removed the field on purpose, though the documentation has not been updated on where the host should be set now (not to mention that it still says you should find the startstop script, not look in the tcollector script).

Also, can tcollector be integrated to collect statsd metrics from a service?

Cheers!

**Comment by RuralHunter** [comment]
Yes, it's very serious that the tool is totally not functional now and there is nothing mentioned in any doc!

**Comment by RuralHunter** [comment]
well, I found where to configure the opentsdb server address. It's in collectors/etc/config.py

**Comment by johann8384** [comment]
I need to update the documentation, I'm going to work on getting the next minor release out with these fixes.
Configuration works like this now, the first step is to load the [defaults](https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L815) from the [configuration file](https://github.com/OpenTSDB/tcollector/blob/master/collectors/etc/config.py#L50). If that fails, it will load the hard-coded [defaults](https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L819). Once defaults have been loaded, it will parse the [command line options](https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L862).

This makes it easier to manage the configuration with a CM setup, like Puppet or similar while still allowing folks to use the command line arguments.

**Comment by johann8384** [comment]
opentsdb.net has been updated.
