### ISSUE TITLE
de-duplication of timestamps in milliseconds

### ISSUE THREAD

**Issue by noodle10000** [OpenTSDB/tcollector#329]
Hi,

The dedup parameter is in seconds, but this means that if the timestamps are in milliseconds we don't see the benefit of dedup.

Would it be possible to scale the comparion with the dedup parameter by 1000 if the timestamp has 11 characters or more (i.e. much like MAX_REASONABLE_TIMESTAMP)? 

Thanks!

**Comment by johann8384** [comment]
I need to go and add "real" support for ms timestamps. There are a few bogus assumptions in the code.
