### ISSUE TITLE
How to start tcollector?

### ISSUE THREAD

**Issue by porunov** [OpenTSDB/tcollector#330]
Documentation says that there is startstop script but it now missing. I wonder to know how to properly start tcollector on centos.

**Comment by vitaliyf** [comment]
https://github.com/OpenTSDB/tcollector/blob/master/tcollector

**Comment by vasiliyk** [comment]
Hello Alexandr .

The documentations as usual remains behind.
If you get source code from git you can run tcollector.py directly or use package for your favourite OS.

Please, ask further questions on mailing list : https://groups.google.com/forum/#!forum/opentsdb
