### ISSUE TITLE
Unble to create rpm using tcollector/rpm

### ISSUE THREAD

**Issue by neerajtiwar** [OpenTSDB/tcollector#331]
I am trying to create RPM using the rpm instructions given for tcollector/rpm but got below error:-

make all
set -e; { \
          echo "# File generated by Makefile, do not edit"; \
	  sed \
            -e 's/@PACKAGE_VERSION@/1.3.1/' \
            -e 's/@PYTHON_VERSION@/2.6/' \
            -e "s/@GIT_SHORTSHA1@/`git rev-list --pretty=format:%h HEAD --max-count=1 | sed 1d || echo unknown`/" \
            -e "s/@GIT_FULLSHA1@/`git rev-list --pretty=format:%H HEAD --max-count=1 | sed 1d || echo unknown`/" \
            -e 's/@RPM_REVISION@/1/' \
	    tcollector.spec; \
        } >tcollector-t.spec
rpmbuild --define "_topdir %(pwd)/" \
          --define "_sourcedir %(pwd)/dist/" \
          --define "_rpmdir %(pwd)" \
          --define "_srcrpmdir %{_topdir}" \
          -ba tcollector-t.spec
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.LD9mP7
+ umask 022
+ cd /root/tcollector/rpm//BUILD
+ '[' /root/tcollector/rpm/BUILDROOT/tcollector-1.3.1-1.x86_64 '!=' / ']'
+ rm -rf /root/tcollector/rpm/BUILDROOT/tcollector-1.3.1-1.x86_64
++ dirname /root/tcollector/rpm/BUILDROOT/tcollector-1.3.1-1.x86_64
+ mkdir -p /root/tcollector/rpm/BUILDROOT
+ mkdir /root/tcollector/rpm/BUILDROOT/tcollector-1.3.1-1.x86_64
+ LANG=C
+ export LANG
+ unset DISPLAY
+ mkdir -p /root/tcollector/rpm/BUILDROOT/tcollector-1.3.1-1.x86_64//usr/local/tcollector/collectors/0/
+ mkdir -p /root/tcollector/rpm/BUILDROOT/tcollector-1.3.1-1.x86_64/etc/init.d/
+ /usr/bin/perl -pe 's/HOMEDIR//usr/local/tcollector/;' -i /root/tcollector/rpm//../rpm/initd.sh
Bareword found where operator expected at -e line 1, near "s/HOMEDIR//usr"
syntax error at -e line 1, near "s/HOMEDIR//usr"
Execution of -e aborted due to compilation errors.
error: Bad exit status from /var/tmp/rpm-tmp.LD9mP7 (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.LD9mP7 (%install)

Please help me to resolve this issue.

**Comment by benrubson** [comment]
See #340 for a fix 👍
