### ISSUE TITLE
How to start tcollector

### ISSUE THREAD

**Issue by shivam009** [OpenTSDB/tcollector#334]
Since startstop script is now renamed as tcollector, and all the documentations are still pointing the old name, so can you tell me how do i start tcollector now? and where do i write the line : TSD_HOST=****

**Comment by shivam009** [comment]
Resolved. thanks

**Comment by his1devil** [comment]
@shivam009  The solution is ? Thanks

**Comment by rraj123** [comment]
How did you solve this?. What is the solution?.
