### ISSUE TITLE
Generic JSON endpoint collector

### ISSUE THREAD

**Issue by srirachapills** [OpenTSDB/tcollector#357]
Do you guys have a collector that just invokes a local http endpoint and expect a json object of metrics? Does that even make sense? Main objective is to allow any web app, regardless of tech stack, to expose a metric endpoint.

I started something that I might be able to contribute to the project. If you have some ideas on some of the feature I should support, let me know as well.

Best regards.

**Comment by johann8384** [comment]
There is not one of these that I recall currently. Something that would be compatible with the output of a Dropwizard metrics endpoint would be good. Maybe a flag for a very generic format, perhaps an array of metric, timestamp, value, tags, and a mode that parses the dropwizard output.

**Comment by johann8384** [comment]
I've implemented a Prometheus Exporter collector that should work with the OpenMetrics standard. #448
