### ISSUE TITLE
Not able to send multiple data points(more than 64) at a time on HTTP API

### ISSUE THREAD

**Issue by veerendra2** [OpenTSDB/tcollector#365]
Hello,
While checking tcollector, I found that, if there are more data points like 160, the TSDB is not accepting: it is throwing HTTP response code 400 `The reason provided was:Chunked request not supported.`

Then I found the issue-->https://github.com/OpenTSDB/opentsdb/issues/324.

I did `tsd.http.request.enable_chunked == true` and increased `tsd.http.request.max_chunk_siz` to 14000, after that I was able to send 70 data points but not more that that. Why tcollector is trying to send more data points at time? or am I missing anything? or should I break down the json dictionary into multiple?

**Example data points**
```
[
   {
      "timestamp":1488964600,
      "metric":"net.sockstat.num_sockets",
      "value":102.0,
      "tags":{
         "host":"ultron",
         "type":"tcp"
      }
   },
   {
      "timestamp":1488964600,
      "metric":"net.sockstat.num_timewait",
      "value":17.0,
      "tags":{
         "host":"ultron"
      }
   },
   {
      "timestamp":1488964600,
      "metric":"net.sockstat.sockets_inuse",
      "value":79.0,
      "tags":{
         "host":"ultron",
         "type":"tcp"
      }
   }
]
```

**Comment by johann8384** [comment]
Well, tCollector isn't normally used with the HTTP API. It looks like changes in OpenTSDB should fix this now.
