### ISSUE TITLE
TCollector doesn't allow tag host=hbase:16020 due to colon not being permitted in tags regex

### ISSUE THREAD

**Issue by HariSekhon** [OpenTSDB/tcollector#406]
Tags such as 
```
host=myhost:16020
```
are rejected by TCollector due to the following regex in tcollector.py:
```
'((?:\s+[-_./a-zA-Z0-9]+=[-_./a-zA-Z0-9]+)*)$', # Tags
```
at line https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L341

This means collectors I have written to collect things like TSD's own region_clients metrics which have a field called endpoint containing '/hostname:16020' pointing to the HBase server are now allowed as tags and I end up having to strip the port off.

It's a simple fix to the regex, question is - is there any reason why colons are not allowed in TCollector / OpenTSDB tags?

**Comment by johann8384** [comment]
the port should be a separate tag. So either replace the : with a -/_ or something, or add host=hostname and port=16020 tags
