### ISSUE TITLE
netfilter collector does not work with recent kernels

### ISSUE THREAD

**Issue by jllorente** [OpenTSDB/tcollector#407]
The netfilter tcollector does not work in Debian with kernel 4.9.
For example, the new location for the conntrack count is /proc/sys/net/netfilter/nf_conntrack_count 

https://github.com/OpenTSDB/tcollector/blob/master/collectors/0/netfilter.py

**Comment by King-Joakim** [comment]
Any updates on this?

**Comment by jllorente** [comment]
Hi @johann8384 , any updates available?

**Comment by johann8384** [comment]
@jllorente @King-Joakim I don't run Debian anywhere but it looks like the collector would just need to have the basedir updated and the STATS updated. Feel free to submit a PR, if you have a system to run it on I imagine this could be done in an hour.
