### ISSUE TITLE
Monitoring API for tcollector

### ISSUE THREAD

**Issue by itamarst** [OpenTSDB/tcollector#421]
It would be nice to be able to check the status of a running tcollector—what collectors it is running, what their status is, etc..

The simplest way I can think of doing this:

* Run HTTP server on some port.
* The HTTP server returns a JSON document.
* The JSON document is a list of objects, where each object maps to a `tcollector.Collector` instance and exposes some of the information in that object.

Does this sound reasonable? If I submitted a PR would it be considered?

**Comment by itamarst** [comment]
@HariSekhon @johann8384 is this something you'd be willing to consider? Any thoughts on design I proposed?

**Comment by johann8384** [comment]
I think this is a GREAT idea!
