### ISSUE TITLE
Much of the metric is filtered out due to Unicode encoding issues in hadoop_http.py

### ISSUE THREAD

**Issue by xujianzhen** [OpenTSDB/tcollector#436]
When hbase metric is collected through collector in the poll() method of hadoop_http.py, when value is of type Unicode, it is filtered by is_numeric, which determines whether value is a (int, long, float) and subclass.Hence the need for compatibility with Unicode types

**Comment by xujianzhen** [comment]
And I already mentioned pr

**Comment by bjozet** [comment]
PR #437 is merged, this can be closed.
