### ISSUE TITLE
Broken logging with default configuration.

### ISSUE THREAD

**Issue by bjozet** [OpenTSDB/tcollector#442]
If running the default configuration (atleast on debian), logging breaks.
The default configuration sets:
1. user running the scripts/collectors/daemons is `tcollector`.
2. path for logfile is `/var/log/tcollector.log`.
3. `max_bytes` is set to 64MB.

This leads to setting `backup_count` to `1` at [L1077](https://github.com/OpenTSDB/tcollector/blob/master/tcollector.py#L1077).
And when the size of log file reach 64mb, it tries to rotate file, but fails because `tcollector` user lacks permissions to create files in `/var/log/`.

Either:
1. Remove `RotatingFileHandler`, `backup_count` and `max_bytes`. Let os/system handle it via `logrotate` (which is way better at it anyways).
2. Move logs to `/var/log/tcollector/` directory, and set permissions on that folder via `chown -R <tcollector_user>:<tcollector_group>`.
3. Some other solution that I fail to think of at the moment.

I can provide PR for whatever solution you guys feel preferable, but I wanted to have the discussion first.

**Comment by johann8384** [comment]
Please feel free to open a PR, I believe letting the system handle it, option 1, sounds best.
