### ISSUE TITLE
Travis CI to GitHub Actions migration

### ISSUE THREAD

**Issue by vasiliyk** [OpenTSDB/tcollector#468]
Team, I am considering migration from Travis CI to GitHub Actions of tcollector repo.

Do you have any opinions?

Also I will remove check for python 2.7 as we dropped in version 1.3.3 support for "Python 2.x, <=3.4.x" as per https://github.com/OpenTSDB/tcollector/blob/master/CHANGELOG.md

cc: @tsuna , @johann8384 , @manolama

**Comment by vasiliyk** [comment]
implemented with commit https://github.com/OpenTSDB/tcollector/commit/9f4727868bd60d85a81f8437a9c460fc6e8f33cb

**Comment by johann8384** [comment]
I am 100% Ok with using Github Actions. I'm not able to really be involved in this project these days so I support whatever is best for those who are involved.
