### ISSUE TITLE
Refactor sysload.py freebsd collector, remove linux related functionality

### ISSUE THREAD

**Issue by vasiliyk** [OpenTSDB/tcollector#471]
Refactor: remove linux related functionality

Collector located at [collectors/available/freebsd/long-lived/sysload.py](https://github.com/OpenTSDB/tcollector/blob/master/collectors/available/freebsd/long-lived/sysload.py)

**Comment by hudakjakub** [comment]
Hello @vasiliyk , I would like to help you with this refactor, you can assign it to me

**Comment by hudakjakub** [comment]
Hello, I create git pull request for this issue https://github.com/OpenTSDB/tcollector/pull/472

**Comment by vasiliyk** [comment]
Merged to master with commit https://github.com/OpenTSDB/tcollector/commit/6b7a4253b2f8d91b81ce725c8e74b5f162fbd0f9.
Thank you for contributing!

**Comment by vasiliyk** [comment]
@hudakjakub, are you interested in creating additional FreeBSD collectors similar to linux ones that tcollector has?
I can list them or create initial drafts so you can continue.

**Comment by vasiliyk** [comment]
implemented
